// Моковые данные для демо на Vercel (без БД)

export const mockLeads = [
  {
    id: '1',
    name: 'Анна Петрова',
    phone: '+7 (999) 123-45-67',
    city: 'Москва',
    source: 'Яндекс.Директ',
    status: 'Новый',
    segment: 'Новостройка',
    subsegment: 'Бетон',
    objectType: 'Квартира',
    finishingType: 'Бетон',
    scenario: 'Полный ремонт с нуля',
    area: '60-80 кв.м',
    rooms: '2',
    keyDate: new Date('2026-09-01'),
    budgetRange: '3-4 млн',
    timeline: '4-5 месяцев',
    decisionMaker: 'Совместно с мужем',
    mainPain: 'Не знаю с чего начать',
    mainObjection: null,
    needsDesign: true,
    needsRepair: true,
    needsCompletion: true,
    needsFurniture: true,
    needsKitchen: true,
    needsBathroom: true,
    needsAcceptance: true,
    hasDesigner: false,
    hasContractor: false,
    hasProject: false,
    fitScore: 85,
    intentScore: 70,
    leadGrade: 'A',
    createdAt: new Date('2026-06-01'),
    updatedAt: new Date('2026-06-01'),
  },
  {
    id: '2',
    name: 'Дмитрий Соколов',
    phone: '+7 (999) 234-56-78',
    city: 'Москва',
    source: 'Instagram',
    status: 'Новый',
    segment: 'Новостройка',
    subsegment: 'Whitebox',
    objectType: 'Квартира',
    finishingType: 'Whitebox',
    scenario: 'Ремонт поверх whitebox',
    area: '80-100 кв.м',
    rooms: '3',
    keyDate: new Date('2026-08-15'),
    budgetRange: '4-5 млн',
    timeline: '3-4 месяца',
    decisionMaker: 'Сам',
    mainPain: 'Хочу быстро въехать',
    mainObjection: null,
    needsDesign: true,
    needsRepair: true,
    needsCompletion: false,
    needsFurniture: true,
    needsKitchen: true,
    needsBathroom: false,
    needsAcceptance: false,
    hasDesigner: false,
    hasContractor: false,
    hasProject: false,
    fitScore: 75,
    intentScore: 80,
    leadGrade: 'A',
    createdAt: new Date('2026-06-02'),
    updatedAt: new Date('2026-06-02'),
  },
  {
    id: '3',
    name: 'Елена Краснова',
    phone: '+7 (999) 345-67-89',
    city: 'Москва',
    source: 'Рекомендация',
    status: 'Новый',
    segment: 'Вторичка',
    subsegment: 'Косметический ремонт',
    objectType: 'Квартира',
    finishingType: null,
    scenario: 'Косметика + мебель',
    area: '50-60 кв.м',
    rooms: '1',
    keyDate: null,
    budgetRange: '1-2 млн',
    timeline: '1-2 месяца',
    decisionMaker: 'Сама',
    mainPain: 'Старая мебель и отделка',
    mainObjection: null,
    needsDesign: false,
    needsRepair: true,
    needsCompletion: false,
    needsFurniture: true,
    needsKitchen: true,
    needsBathroom: false,
    needsAcceptance: false,
    hasDesigner: false,
    hasContractor: false,
    hasProject: false,
    fitScore: 45,
    intentScore: 60,
    leadGrade: 'C',
    createdAt: new Date('2026-06-03'),
    updatedAt: new Date('2026-06-03'),
  },
  {
    id: '4',
    name: null,
    phone: '+7 (999) 456-78-90',
    city: 'Московская область',
    source: 'Avito',
    status: 'Новый',
    segment: 'Новостройка',
    subsegment: 'Чистовая',
    objectType: 'Квартира',
    finishingType: 'Чистовая',
    scenario: 'Сохранение отделки',
    area: '40-50 кв.м',
    rooms: '1',
    keyDate: new Date('2026-07-01'),
    budgetRange: '500-700 тыс',
    timeline: '1 месяц',
    decisionMaker: 'Родители помогают',
    mainPain: 'Не нравится планировка',
    mainObjection: null,
    needsDesign: false,
    needsRepair: false,
    needsCompletion: false,
    needsFurniture: true,
    needsKitchen: false,
    needsBathroom: false,
    needsAcceptance: false,
    hasDesigner: false,
    hasContractor: false,
    hasProject: false,
    fitScore: 30,
    intentScore: 50,
    leadGrade: 'D',
    createdAt: new Date('2026-06-03'),
    updatedAt: new Date('2026-06-03'),
  },
];

export const mockScripts = [
  {
    id: '1',
    category: 'greeting',
    segment: null,
    subsegment: null,
    title: 'Приветствие (холодный звонок)',
    text: 'Добрый день! Меня зовут [Имя], я из студии дизайна [Название]. Вы оставляли заявку на консультацию по ремонту квартиры. Удобно сейчас говорить пару минут?',
    sortOrder: 1,
    createdAt: new Date(),
  },
  {
    id: '2',
    category: 'qualification',
    segment: 'Новостройка',
    subsegment: null,
    title: 'Тип отделки в новостройке',
    text: 'Отлично! Скажите, квартира в новостройке — какая там сейчас отделка? Бетон, whitebox или уже с чистовой?',
    sortOrder: 2,
    createdAt: new Date(),
  },
  {
    id: '3',
    category: 'value',
    segment: 'Новостройка',
    subsegment: 'Бетон',
    title: 'Ценность работы под ключ',
    text: 'Для квартир с бетоном мы делаем полный цикл: дизайн-проект → ремонт → комплектация материалами → мебель под размеры. Вы общаетесь с одной командой, а не координируете 5 подрядчиков. Экономия времени и нервов — огромная.',
    sortOrder: 10,
    createdAt: new Date(),
  },
  {
    id: '4',
    category: 'objection',
    segment: null,
    subsegment: null,
    title: 'Возражение: Дорого',
    text: 'Понимаю. Давайте посмотрим по-другому: если вы сами будете искать дизайнера, бригаду, закупать материалы, заказывать мебель — сколько времени это займёт? А если где-то ошибётесь — переделка стоит ещё дороже. Мы берём эти риски на себя.',
    sortOrder: 100,
    createdAt: new Date(),
  },
  {
    id: '5',
    category: 'close',
    segment: null,
    subsegment: null,
    title: 'Назначение встречи',
    text: 'Отлично! Давайте встретимся, покажу примеры похожих проектов и посчитаем примерную смету. Вам удобнее в четверг или в пятницу?',
    sortOrder: 200,
    createdAt: new Date(),
  },
];
